### ISSUE TITLE
Improve events style formular 

### ISSUE THREAD

**Issue by J0MS** [underneath-systems/event-management-app#18]
Improve css style for the endpoints:

events/create
events/update
events/delete

Use the following file as template:
[https://github.com/underneath-systems/event-management-app/blob/master/templates/registration/login.html](url)

**Comment by J0MS** [comment]
@mijail73 ya tenemos la cuenta de correo? Para hacer pruebas este lunes.

**Comment by mijail73** [comment]
it's done

**Comment by J0MS** [comment]
@mijail73 Revisa la nueva version del archivo plantilla, asi deben quedar las demas.
