### ISSUE TITLE
Coherencia al establecer las fechas de los eventos

### ISSUE THREAD

**Issue by lixbeth5** [underneath-systems/event-management-app#31]
La fecha para programar un evento debe comenzar con el día presente(no se debe poder organizar eventos en fechas ya pasadas) y terminar el mismo día o después .

**Comment by J0MS** [comment]
Listo!

**Comment by J0MS** [comment]
Aunque faltaria ajustar los dias para que solo sea posible crear eventos a partir de dia actual
